[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

